# wpt api key
k: A.6e0139459cbacdff3e1a8632986ca800

# test target
url: https://lamp-post.sparkboxqa.com
label: "<%= DateTime.now %> Lamp Post WPT"

# response format
f: json

# http auth user/pass
login: <%= ENV["WPT_USER"] %>
password: <%= ENV["WPT_PASSWORD"] %>

# pingback url
pingback: http://iamnathanj.com/test-results
